Working... ---------------------------------------- 100% 0:00:04
Run started:2024-02-10 21:18:43.063885

Test results:
>> Issue: [B303:blacklist] Use of insecure MD2, MD4, MD5, or SHA1 hash function.
   Severity: Medium   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/blacklists/blacklist_calls.html#b303-md5
   Location: .\asyncssh\crypto\pyca\dsa.py:95:40
94	
95	        return self.pyca_key.sign(data, SHA1())
96	

--------------------------------------------------
>> Issue: [B303:blacklist] Use of insecure MD2, MD4, MD5, or SHA1 hash function.
   Severity: Medium   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/blacklists/blacklist_calls.html#b303-md5
   Location: .\asyncssh\crypto\pyca\dsa.py:115:44
114	        try:
115	            self.pyca_key.verify(sig, data, SHA1())
116	            return True

--------------------------------------------------
>> Issue: [B303:blacklist] Use of insecure MD2, MD4, MD5, or SHA1 hash function.
   Severity: Medium   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/blacklists/blacklist_calls.html#b303-md5
   Location: .\asyncssh\crypto\pyca\rsa.py:45:19
44	        else:
45	            return SHA1()
46	

--------------------------------------------------
>> Issue: [B324:hashlib] Use of weak MD5 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b324_hashlib.html
   Location: .\asyncssh\kex.py:92:52
91	            for mech in mechs:
92	                suffix = b'-' + binascii.b2a_base64(md5(mech).digest())[:-1]
93	                expanded_kex_algs.append(alg + suffix)

--------------------------------------------------
>> Issue: [B108:hardcoded_tmp_directory] Probable insecure usage of temp file/directory.
   Severity: Medium   Confidence: Medium
   CWE: CWE-377 (https://cwe.mitre.org/data/definitions/377.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b108_hardcoded_tmp_directory.html
   Location: .\asyncssh\x11.py:253:34
252	            self._connect_coro = loop.create_unix_connection
253	            self._connect_args = ('/tmp/.X11-unix/X' + dpynum,)
254	        else:

--------------------------------------------------
>> Issue: [B108:hardcoded_tmp_directory] Probable insecure usage of temp file/directory.
   Severity: Medium   Confidence: Medium
   CWE: CWE-377 (https://cwe.mitre.org/data/definitions/377.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b108_hardcoded_tmp_directory.html
   Location: .\examples\chroot_sftp_server.py:26:15
25	    def __init__(self, conn):
26	        root = '/tmp/sftp/' + conn.get_extra_info('username')
27	        os.makedirs(root, exist_ok=True)

--------------------------------------------------
>> Issue: [B108:hardcoded_tmp_directory] Probable insecure usage of temp file/directory.
   Severity: Medium   Confidence: Medium
   CWE: CWE-377 (https://cwe.mitre.org/data/definitions/377.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b108_hardcoded_tmp_directory.html
   Location: .\examples\redirect_input.py:19:60
18	    async with asyncssh.connect('localhost') as conn:
19	        await conn.run('tail -r', input='1\n2\n3\n', stdout='/tmp/stdout')
20	

--------------------------------------------------
>> Issue: [B404:blacklist] Consider possible security implications associated with the subprocess module.
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/blacklists/blacklist_imports.html#b404-import-subprocess
   Location: .\examples\redirect_local_pipe.py:15:0
14	
15	import asyncio, asyncssh, subprocess, sys
16	

--------------------------------------------------
>> Issue: [B607:start_process_with_partial_path] Starting a process with a partial executable path
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b607_start_process_with_partial_path.html
   Location: .\examples\redirect_local_pipe.py:19:21
18	    async with asyncssh.connect('localhost') as conn:
19	        local_proc = subprocess.Popen(r'echo "1\n2\n3"', shell=True,
20	                                      stdout=subprocess.PIPE)
21	        remote_result = await conn.run('tail -r', stdin=local_proc.stdout)

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True seems safe, but may be changed in the future, consider rewriting without shell
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: .\examples\redirect_local_pipe.py:19:21
18	    async with asyncssh.connect('localhost') as conn:
19	        local_proc = subprocess.Popen(r'echo "1\n2\n3"', shell=True,
20	                                      stdout=subprocess.PIPE)
21	        remote_result = await conn.run('tail -r', stdin=local_proc.stdout)

--------------------------------------------------
>> Issue: [B404:blacklist] Consider possible security implications associated with the subprocess module.
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/blacklists/blacklist_imports.html#b404-import-subprocess
   Location: .\examples\redirect_server.py:22:0
21	
22	import asyncio, asyncssh, subprocess, sys
23	

--------------------------------------------------
>> Issue: [B607:start_process_with_partial_path] Starting a process with a partial executable path
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b607_start_process_with_partial_path.html
   Location: .\examples\redirect_server.py:25:14
24	async def handle_client(process):
25	    bc_proc = subprocess.Popen('bc', shell=True, stdin=subprocess.PIPE,
26	                               stdout=subprocess.PIPE, stderr=subprocess.PIPE)
27	

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True seems safe, but may be changed in the future, consider rewriting without shell
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: .\examples\redirect_server.py:25:14
24	async def handle_client(process):
25	    bc_proc = subprocess.Popen('bc', shell=True, stdin=subprocess.PIPE,
26	                               stdout=subprocess.PIPE, stderr=subprocess.PIPE)
27	

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b102_exec_used.html
   Location: .\setup.py:35:4
34	with open(path.join(base_dir, 'asyncssh', 'version.py')) as version:
35	    exec(version.read())
36	

--------------------------------------------------
>> Issue: [B404:blacklist] Consider possible security implications associated with the subprocess module.
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/blacklists/blacklist_imports.html#b404-import-subprocess
   Location: .\tests\server.py:20:0
19	import socket
20	import subprocess
21	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'passphrase'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\server.py:93:8
92	        ckey.write_private_key('ckey')
93	        ckey.write_private_key('ckey_encrypted', passphrase='passphrase')
94	        ckey.write_public_key('ckey.pub')

--------------------------------------------------
>> Issue: [B404:blacklist] Consider possible security implications associated with the subprocess module.
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/blacklists/blacklist_imports.html#b404-import-subprocess
   Location: .\tests\test_agent.py:19:0
18	import signal
19	import subprocess
20	import unittest

--------------------------------------------------
>> Issue: [B103:set_bad_file_permissions] Chmod setting a permissive mask 0o755 on file (ssh-askpass).
   Severity: Medium   Confidence: High
   CWE: CWE-732 (https://cwe.mitre.org/data/definitions/732.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b103_set_bad_file_permissions.html
   Location: .\tests\test_agent.py:100:12
99	            f.write('#!/bin/sh\nexit %d\n' % status)
100	            os.chmod('ssh-askpass', 0o755)
101	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'password'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_auth.py:540:23
539	        with self.subTest('Incorrect password'):
540	            yield from self.check_auth(b'password', (False, None),
541	                                       password_auth=True, password='password')
542	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'password'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_auth.py:544:23
543	        with self.subTest('Correct password'):
544	            yield from self.check_auth(b'password', (True, None),
545	                                       password_auth=True, password='password',
546	                                       success=True)
547	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'password'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_auth.py:549:23
548	        with self.subTest('Password change not available'):
549	            yield from self.check_auth(b'password', (False, None),
550	                                       password_auth=True, password='password',
551	                                       password_change_prompt='change')
552	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'password'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_auth.py:555:27
554	            with self.assertRaises(DisconnectError):
555	                yield from self.check_auth(b'password', (False, False),
556	                                           password_auth=True,
557	                                           password='password',
558	                                           password_change=True,
559	                                           password_change_prompt=b'\xff')
560	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'password'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_auth.py:562:23
561	        with self.subTest('Password change failed'):
562	            yield from self.check_auth(b'password', (False, False),
563	                                       password_auth=True, password='password',
564	                                       password_change=True,
565	                                       password_change_prompt='change')
566	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'password'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_auth.py:568:23
567	        with self.subTest('Password change succeeded'):
568	            yield from self.check_auth(b'password', (True, True),
569	                                       password_auth=True, password='password',
570	                                       password_change=True,
571	                                       password_change_prompt='change',
572	                                       success=True)
573	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: ''
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_connection.py:1020:40
1019	        with self.assertRaises(asyncio.TimeoutError):
1020	            yield from asyncio.wait_for(self.connect(username='user',
1021	                                                     password=''), 0.5)
1022	

--------------------------------------------------
>> Issue: [B105:hardcoded_password_string] Possible hardcoded password: 'oldpw'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b105_hardcoded_password_string.html
   Location: .\tests\test_connection_auth.py:181:23
180	
181	        if password == 'oldpw':
182	            raise asyncssh.PasswordChangeRequired('Password change required')

--------------------------------------------------
>> Issue: [B105:hardcoded_password_string] Possible hardcoded password: 'pw'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b105_hardcoded_password_string.html
   Location: .\tests\test_connection_auth.py:184:31
183	        else:
184	            return password == 'pw'
185	

--------------------------------------------------
>> Issue: [B105:hardcoded_password_string] Possible hardcoded password: 'oldpw'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b105_hardcoded_password_string.html
   Location: .\tests\test_connection_auth.py:189:31
188	
189	        return old_password == 'oldpw'
190	

--------------------------------------------------
>> Issue: [B104:hardcoded_bind_all_interfaces] Possible binding to all interfaces.
   Severity: Medium   Confidence: Medium
   CWE: CWE-605 (https://cwe.mitre.org/data/definitions/605.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b104_hardcoded_bind_all_interfaces.html
   Location: .\tests\test_connection_auth.py:659:66
658	                                CERT_TYPE_USER, skey, ckey, ['ckey'],
659	                                options={'source-address': String('0.0.0.0')})
660	

--------------------------------------------------
>> Issue: [B107:hardcoded_password_default] Possible hardcoded password: ''
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b107_hardcoded_password_default.html
   Location: .\tests\test_connection_auth.py:1003:4
1002	    @asyncio.coroutine
1003	    def _connect_password(self, username, password, old_password='',
1004	                          new_password='', test_async=False):
1005	        """Open a connection to test password authentication"""
1006	
1007	        def client_factory():
1008	            """Return an SSHClient to use to do password change"""
1009	
1010	            cls = _AsyncPasswordClient if test_async else _PasswordClient
1011	            return cls(password, old_password, new_password)
1012	
1013	        conn, _ = yield from self.create_connection(client_factory,
1014	                                                    username=username,
1015	                                                    client_keys=None)
1016	
1017	        return conn
1018	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'pw'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_connection_auth.py:1023:25
1022	
1023	        with (yield from self.connect(username='pw', password='pw',
1024	                                      client_keys=None)) as conn:
1025	            pass

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'badpw'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_connection_auth.py:1034:23
1033	        with self.assertRaises(asyncssh.DisconnectError):
1034	            yield from self.connect(username='pw', password='badpw',
1035	                                    client_keys=None)
1036	

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'kbdint'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_connection_auth.py:1113:25
1112	
1113	        with (yield from self.connect(username='kbdint', password='kbdint',
1114	                                      client_keys=None)) as conn:
1115	            pass

--------------------------------------------------
>> Issue: [B106:hardcoded_password_funcarg] Possible hardcoded password: 'badpw'
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b106_hardcoded_password_funcarg.html
   Location: .\tests\test_connection_auth.py:1124:23
1123	        with self.assertRaises(asyncssh.DisconnectError):
1124	            yield from self.connect(username='kbdint', password='badpw',
1125	                                    client_keys=None)
1126	

--------------------------------------------------
>> Issue: [B104:hardcoded_bind_all_interfaces] Possible binding to all interfaces.
   Severity: Medium   Confidence: Medium
   CWE: CWE-605 (https://cwe.mitre.org/data/definitions/605.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b104_hardcoded_bind_all_interfaces.html
   Location: .\tests\test_forward.py:494:58
493	        with (yield from self.connect()) as conn:
494	            listener = yield from conn.forward_local_port('0.0.0.0', 0,
495	                                                          '', 7)
496	

--------------------------------------------------
>> Issue: [B404:blacklist] Consider possible security implications associated with the subprocess module.
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/blacklists/blacklist_imports.html#b404-import-subprocess
   Location: .\tests\test_public_key.py:26:0
25	import shutil
26	import subprocess
27	import sys

--------------------------------------------------
>> Issue: [B103:set_bad_file_permissions] Chmod setting a permissive mask 0o1234 on file (file).
   Severity: Medium   Confidence: High
   CWE: CWE-732 (https://cwe.mitre.org/data/definitions/732.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b103_set_bad_file_permissions.html
   Location: .\tests\test_sftp.py:880:23
879	            self._create_file('file')
880	            yield from sftp.chmod('file', 0o1234)
881	            self.assertEqual(stat.S_IMODE(os.stat('file').st_mode), 0o1234)

--------------------------------------------------
>> Issue: [B103:set_bad_file_permissions] Chmod setting a permissive mask 0o755 on file (dst).
   Severity: Medium   Confidence: High
   CWE: CWE-732 (https://cwe.mitre.org/data/definitions/732.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b103_set_bad_file_permissions.html
   Location: .\tests\test_sftp.py:3168:12
3167	        finally:
3168	            os.chmod('dst', 0o755)
3169	            remove('src dst')

--------------------------------------------------
>> Issue: [B404:blacklist] Consider possible security implications associated with the subprocess module.
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/blacklists/blacklist_imports.html#b404-import-subprocess
   Location: .\tests\util.py:19:0
18	import os
19	import subprocess
20	import sys

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.7/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: .\tests\util.py:179:15
178	    try:
179	        return subprocess.check_output(cmd, shell=True,
180	                                       stderr=subprocess.STDOUT)
181	    except subprocess.CalledProcessError as exc: # pragma: no cover

--------------------------------------------------

Code scanned:
	Total lines of code: 33195
	Total lines skipped (#nosec): 0
	Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0
		Low: 26
		Medium: 12
		High: 2
	Total issues (by confidence):
		Undefined: 0
		Low: 0
		Medium: 21
		High: 19
Files skipped (0):
