"Incomplete URL substring sanitization","Security checks on the substrings of an unparsed URL are often vulnerable to bypassing.","warning","The string [[""https://example.com""|""relative:///tests/functional/test_routes.py:101:12:101:33""]] may be at an arbitrary position in the sanitized URL.","/tests/functional/test_routes.py","101","12","101","46"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///archivy/api.py:1:38:1:44""]].
This path depends on a [[""user-provided value""|""relative:///archivy/routes.py:11:5:11:11""]].","/archivy/data.py","24","9","24","16"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///archivy/routes.py:11:5:11:11""]].","/archivy/data.py","58","21","58","29"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///archivy/routes.py:11:5:11:11""]].","/archivy/data.py","101","55","101","63"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///archivy/routes.py:11:5:11:11""]].","/archivy/data.py","107","25","107","33"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///archivy/api.py:1:38:1:44""]].","/archivy/data.py","304","9","304","16"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///archivy/api.py:1:38:1:44""]].","/archivy/data.py","316","23","316","32"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///archivy/api.py:1:38:1:44""]].","/archivy/data.py","429","11","429","19"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///archivy/api.py:1:38:1:44""]].","/archivy/data.py","432","16","432","29"
"Uncontrolled command line","Using externally controlled strings in a command line may allow a malicious user to change the meaning of the command.","error","This command line depends on a [[""user-provided value""|""relative:///archivy/api.py:1:38:1:44""]].","/archivy/search.py","106","14","106","19"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///archivy/api.py:1:38:1:44""]].","/archivy/api.py","199","21","199","34"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///archivy/routes.py:11:5:11:11""]].","/archivy/routes.py","261","29","261","43"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///archivy/routes.py:11:5:11:11""]].","/archivy/routes.py","302","21","302","43"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///archivy/routes.py:11:5:11:11""]].","/archivy/routes.py","314","29","314","51"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///archivy/routes.py:11:5:11:11""]].","/archivy/routes.py","316","21","316","43"
