/tmp/mistune/mistune.py:115:13: DUO138 catastrophic "re" usage - denial-of-service possible
/tmp/mistune/mistune.py:453:12: DUO138 catastrophic "re" usage - denial-of-service possible
/tmp/mistune/mistune.py:460:15: DUO138 catastrophic "re" usage - denial-of-service possible
/tmp/mistune/mistune.py:465:14: DUO138 catastrophic "re" usage - denial-of-service possible
/tmp/mistune/mistune.py:472:16: DUO138 catastrophic "re" usage - denial-of-service possible
