/tmp/urllib3/dummyserver/server.py:34:18: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/dummyserver/server.py:254:24: DUO102 insecure use of "random" module, prefer "random.SystemRandom"
/tmp/urllib3/src/urllib3/contrib/pyopenssl.py:80:5: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/pyopenssl.py:91:31: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/pyopenssl.py:96:5: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/pyopenssl.py:97:5: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:127:5: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:131:26: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:135:26: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:151:26: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:151:67: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/contrib/securetransport.py:742:55: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/src/urllib3/packages/six.py:699:9: DUO105 use of "exec" is insecure
/tmp/urllib3/test/test_exceptions.py:29:18: DUO103 insecure use of "pickle" or "cPickle"
/tmp/urllib3/test/test_util.py:388:13: DUO131 "urllib3" warnings disabled, insecure connections possible
/tmp/urllib3/test/test_util.py:475:16: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/test_util.py:476:10: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/test_util.py:476:25: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/test_util.py:488:10: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/test_util.py:488:31: DUO122 insecure "ssl" module attribute use
/tmp/urllib3/test/with_dummyserver/test_https.py:296:16: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:413:22: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:425:22: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:474:22: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_https.py:482:22: DUO132 "urllib3" certificate verification disabled, insecure connections possible
/tmp/urllib3/test/with_dummyserver/test_socketlevel.py:101:25: DUO122 insecure "ssl" module attribute use
