/tmp/jupyter_core/jupyter_core/tests/test_paths.py:420:16: DUO106 insecure use of "os" module
