/tmp/yolapi/yolapi/importer/tasks.py:119:14: DUO130 insecure use of "hashlib" module
/tmp/yolapi/yolapi/pypi/metadata.py:135:8: DUO138 catastrophic "re" usage - denial-of-service possible
/tmp/yolapi/yolapi/pypi/upload.py:176:11: DUO130 insecure use of "hashlib" module
