/tmp/django-openipam/openipam/conf/settings.py:112:5: DUO130 insecure use of "hashlib" module
/tmp/django-openipam/openipam/core/context_processors.py:11:25: DUO130 insecure use of "hashlib" module
/tmp/django-openipam/openipam/core/views.py:227:13: DUO102 insecure use of "random" module, prefer "random.SystemRandom"
/tmp/django-openipam/openipam/hosts/models.py:165:37: DUO102 insecure use of "random" module, prefer "random.SystemRandom"
/tmp/django-openipam/openipam/hosts/models.py:166:40: DUO102 insecure use of "random" module, prefer "random.SystemRandom"
/tmp/django-openipam/openipam/hosts/models.py:167:37: DUO102 insecure use of "random" module, prefer "random.SystemRandom"
/tmp/django-openipam/openipam/hosts/models.py:214:30: DUO102 insecure use of "random" module, prefer "random.SystemRandom"
/tmp/django-openipam/openipam/hosts/validators.py:7:15: DUO138 catastrophic "re" usage - denial-of-service possible
